services:
  mysql:
    image: mysql:8.0
    container_name: wordbuilder_mysql
    environment:
      MYSQL_DATABASE: word_builder_game
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data: